### ISSUE TITLE
env file exposed

### ISSUE THREAD

**Issue by leticiabytes** [diogoX451/Repositorios-de-Livros-Node.js#1]
Hey, your .env file are exposed in your project.
You can read [this](https://dev.to/somedood/please-dont-commit-env-3o9h) to understand more about de risks.

**Comment by diogoX451** [comment]
Hi, What' s up?

I already reomvi the .env file, I don't understand why .gitignore missed the file

**Comment by diogoX451** [comment]
Thank you for the tip
